baseurl : "https://titechmeister.github.io/"
languageCode: "ja-jp"
title: "meister online"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"
pagination:
  pagerSize: 5

taxonomies:
  category : "categories"
  tag : "tags"
  series : "series"
  archive : "archives"

menu:
  main:
    - name: 最新情報
      url: "/"
      weight: 1
    - name: 団体情報
      url: "about/"
      weight: 2
    - name: 班紹介
      url: "teams/"
      weight: 3
    - name: アクセス
      url: "access/"
      weight: 4
    - name: 支援
      url: "sponsor/"
      weight: 5
    - name: お問い合わせ
      url: "links/"
      weight: 6

params:
  social:
    twitter: "titech_meister"
    instagram: "tokyotechmeister"
    github: "TitechMeister"
    youtube: "Meistermovie"
  description: "meister online"
  footer: "Copyright &copy; 1992-{Year} Meister. All rights reserved."

markup:
  highlight:
    pygmentsCodefences : true
    style : "monokai"
  goldmark:
    renderer:
      unsafe: true


author:
  name : "Meister Admin"